export const Colors = {
  black: '#000000',
  white: [
    '#ffffff',
    '#f2f2f2',
    '#f6f7f9',
    '#d9dedb',
    '#fdfdfd',
    '#f5f5f5',
    '#F7F7F7',
  ],
  red: '#D93E30',
  dark: '#212121',
  gray: '#4b4b4b',
  darkGray: '#333333',
  lightGray: '#808080',
  yellow: '#F2CB07',
  yellow1: '#F5DB13',
  green: '#73D677',
  grass: '#70A83B',
  water: '#A2CFF0 ',
  fire: '#F76545',
  normal: '#76AADB ',
  poison: '#A974BC ',
  ground: '#9B897B ',
  electric: '#F7C545 ',
  steel: '#A1A1A1',
  flying: '#DBF4FF',
};

export const typeColors = {
  grass: Colors.grass,
  bug: Colors.grass,
  ice: Colors.water,
  water: Colors.water,
  steel: Colors.steel,
  dark: Colors.steel,
  rock: Colors.steel,
  poison: Colors.poison,
  psychic: Colors.poison,
  fairy: Colors.poison,
  normal: Colors.normal,
  ghost: Colors.normal,
  flying: Colors.flying,
  fire: Colors.fire,
  fighting: Colors.fire,
  dragon: Colors.fire,
  ground: Colors.ground,
  unknown: Colors.ground,
  electric: Colors.electric,
  shadow: Colors.steel,
};
